global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@bwadl.com'
  smtp_auth_username: 'alerts@bwadl.com'
  smtp_auth_password: 'your-email-password'

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 4h

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@bwadl.com'
        subject: 'Bwadl Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert Details:
          {{ range .Alerts }}
          - Alert: {{ .Annotations.summary }}
          - Description: {{ .Annotations.description }}
          - Severity: {{ .Labels.severity }}
          - Service: {{ .Labels.service }}
          - Started: {{ .StartsAt }}
          {{ end }}
        headers:
          Subject: 'Bwadl Monitoring Alert'

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@bwadl.com,ops@bwadl.com'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Started: {{ .StartsAt }}
          
          This requires immediate attention!
          {{ end }}
    # Uncomment and configure for Slack notifications
    # slack_configs:
    #   - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    #     channel: '#critical-alerts'
    #     title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
    #     text: |
    #       {{ range .Alerts }}
    #       *{{ .Annotations.summary }}*
    #       {{ .Annotations.description }}
    #       Service: {{ .Labels.service }}
    #       {{ end }}
    #     color: 'danger'

  - name: 'warning-alerts'
    email_configs:
      - to: 'ops@bwadl.com'
        subject: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        body: |
          ⚠️ WARNING ALERT ⚠️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Started: {{ .StartsAt }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
