global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Your .NET Application (adjust port based on your configuration)
  - job_name: 'bwadl-api'
    static_configs:
      - targets: ['host.docker.internal:5281']  # HTTP
      # - targets: ['host.docker.internal:7260']  # HTTPS - uncomment if using HTTPS
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
